# Generated by Django 4.1 on 2024-04-07 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnoLetivo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ano", models.IntegerField(null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("BIM", "Bimestre"), ("SEM", "Semestre")],
                        max_length=20,
                        null=True,
                        verbose_name="etapas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=20)),
                ("carga_horaria", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.CreateModel(
            name="ProfessorDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turmas.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turmas.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("professor", "disciplina")},
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=10, unique=True)),
                (
                    "id_curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="turmas.curso"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=10, unique=True)),
                ("vagas", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
                (
                    "anoLetivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turmas.anoletivo",
                    ),
                ),
                (
                    "professores_disciplinas",
                    models.ManyToManyField(
                        related_name="turmas", to="turmas.professordisciplina"
                    ),
                ),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="turmas.serie"
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="turmas.turno"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="professor",
            name="disciplinas",
            field=models.ManyToManyField(
                related_name="professores",
                through="turmas.ProfessorDisciplina",
                to="turmas.disciplina",
            ),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="series",
            field=models.ManyToManyField(related_name="disciplinas", to="turmas.serie"),
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Etapa")),
                (
                    "data_inicio",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_termino",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Data de Término"
                    ),
                ),
                (
                    "ano_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="turmas.anoletivo",
                    ),
                ),
            ],
            options={
                "unique_together": {("ano_letivo", "numero")},
            },
        ),
    ]
